#! /usr/bin/dh-exec
[linux-any] usr/lib/*/directfb-*/*drivers/*.so
usr/lib/*/directfb-*/interfaces/IDirectFBFont/libidirectfbfont_dgiff.so
usr/lib/*/directfb-*/interfaces/IDirectFBImageProvider/libidirectfbimageprovider_dfiff.so
usr/lib/*/directfb-*/interfaces/IDirectFBImageProvider/libidirectfbimageprovider_gif.so
usr/lib/*/directfb-*/interfaces/IDirectFBVideoProvider/libidirectfbvideoprovider_gif.so
usr/lib/*/directfb-*/interfaces/IWater/libiwater_default.so
usr/lib/*/directfb-*/interfaces/IDirectFBWindows/libidirectfbwindows_default.so
[linux-any] usr/lib/*/directfb-*/interfaces/IDirectFBVideoProvider/libidirectfbvideoprovider_v4l.so
usr/lib/*/directfb-*/systems/libdirectfb_devmem.so
usr/lib/*/directfb-*/systems/libdirectfb_dummy.so
[linux-any] usr/lib/*/directfb-*/systems/libdirectfb_fbdev.so
usr/lib/*/directfb-*/wm/libdirectfbwm_default.so
usr/lib/*/libdirectfb-*.so.*
usr/lib/*/libfusion-*.so.*
usr/lib/*/libdirect-*.so.*
usr/share/directfb-*
