usr/lib/*/directfb-*/interfaces/IDirectFBFont/libidirectfbfont_ft2.so
usr/lib/*/directfb-*/interfaces/IDirectFBImageProvider/libidirectfbimageprovider_jpeg.so
usr/lib/*/directfb-*/interfaces/IDirectFBImageProvider/libidirectfbimageprovider_png.so
usr/lib/*/directfb-*/interfaces/IDirectFBImageProvider/libidirectfbimageprovider_mpeg2.so
usr/lib/*/directfb-*/interfaces/IDirectFBImageProvider/libidirectfbimageprovider_bmp.so
usr/lib/*/directfb-*/interfaces/IDirectFBImageProvider/libidirectfbimageprovider_pnm.so
usr/lib/*/directfb-*/systems/libdirectfb_mesa_system.so
usr/lib/*/directfb-*/systems/libdirectfb_x11.so
